/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CodingToolsRouteImport } from './routes/coding-tools'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoriesStorySlugRouteImport } from './routes/stories.$storySlug'

const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingToolsRoute = CodingToolsRouteImport.update({
  id: '/coding-tools',
  path: '/coding-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoriesStorySlugRoute = StoriesStorySlugRouteImport.update({
  id: '/stories/$storySlug',
  path: '/stories/$storySlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/benchmarks': typeof BenchmarksRoute
  '/coding-tools': typeof CodingToolsRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/stories/$storySlug': typeof StoriesStorySlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/coding-tools': typeof CodingToolsRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/stories/$storySlug': typeof StoriesStorySlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/benchmarks': typeof BenchmarksRoute
  '/coding-tools': typeof CodingToolsRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/stories/$storySlug': typeof StoriesStorySlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/benchmarks'
    | '/coding-tools'
    | '/login'
    | '/models'
    | '/stories/$storySlug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmarks'
    | '/coding-tools'
    | '/login'
    | '/models'
    | '/stories/$storySlug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/benchmarks'
    | '/coding-tools'
    | '/login'
    | '/models'
    | '/stories/$storySlug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BenchmarksRoute: typeof BenchmarksRoute
  CodingToolsRoute: typeof CodingToolsRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  StoriesStorySlugRoute: typeof StoriesStorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding-tools': {
      id: '/coding-tools'
      path: '/coding-tools'
      fullPath: '/coding-tools'
      preLoaderRoute: typeof CodingToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/stories/$storySlug': {
      id: '/stories/$storySlug'
      path: '/stories/$storySlug'
      fullPath: '/stories/$storySlug'
      preLoaderRoute: typeof StoriesStorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BenchmarksRoute: BenchmarksRoute,
  CodingToolsRoute: CodingToolsRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  StoriesStorySlugRoute: StoriesStorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
